// Generated by gencpp from file Eurobot_msgs/RobotCoord.msg
// DO NOT EDIT!


#ifndef EUROBOT_MSGS_MESSAGE_ROBOTCOORD_H
#define EUROBOT_MSGS_MESSAGE_ROBOTCOORD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Eurobot_msgs
{
template <class ContainerAllocator>
struct RobotCoord_
{
  typedef RobotCoord_<ContainerAllocator> Type;

  RobotCoord_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  RobotCoord_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> const> ConstPtr;

}; // struct RobotCoord_

typedef ::Eurobot_msgs::RobotCoord_<std::allocator<void> > RobotCoord;

typedef boost::shared_ptr< ::Eurobot_msgs::RobotCoord > RobotCoordPtr;
typedef boost::shared_ptr< ::Eurobot_msgs::RobotCoord const> RobotCoordConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Eurobot_msgs::RobotCoord_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Eurobot_msgs::RobotCoord_<ContainerAllocator1> & lhs, const ::Eurobot_msgs::RobotCoord_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Eurobot_msgs::RobotCoord_<ContainerAllocator1> & lhs, const ::Eurobot_msgs::RobotCoord_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Eurobot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::Eurobot_msgs::RobotCoord_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa130bc60ee651385ULL;
  static const uint64_t static_value2 = 0x5dc62ea83fcc5b20ULL;
};

template<class ContainerAllocator>
struct DataType< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Eurobot_msgs/RobotCoord";
  }

  static const char* value(const ::Eurobot_msgs::RobotCoord_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 theta\n"
;
  }

  static const char* value(const ::Eurobot_msgs::RobotCoord_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotCoord_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Eurobot_msgs::RobotCoord_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Eurobot_msgs::RobotCoord_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EUROBOT_MSGS_MESSAGE_ROBOTCOORD_H
